[project]
name = "murmur"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.16.2",
    "fastapi>=0.115.14",
    "pytest>=8.4.1",
    "sqlalchemy>=2.0.41",
]
